# Generated by Django 4.1 on 2022-11-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_song_id_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
